name: dmd
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bitsdojo_window: ^0.1.1+1
  flutter_svg: ^0.22.0
  hovering: ^1.0.4
  google_fonts: ^2.1.0
  fl_chart: ^0.36.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0


flutter:

  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/logo.svg
    - assets/icons/
    - assets/data/Stories.json
    - assets/data/Rights.json

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
